name: Lint

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1
            - run: bun install
            - run: bun lint
              env:
                  CI: true
